[package]
name = "db-automerge"
version = "0.1.0"
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
async-stream = { version = "0.3", default-features = false, features = [] }
futures = { version = "0.3", default-features = false, features = [
  "std",
  "executor",
] }
uuid = { version = "1.4", default-features = false, features = ["v4"] }
sha2 = { version = "0.10", default-features = false, features = ["std"] }
automerge = { version = "0.9", default-features = false, features = [] }
db-engine = { path = "../db-engine", default-features = false }
async-lock = { version = "3.4", default-features = false, features = ["std"] }
base64 = { version = "0.21", default-features = false, features = ["std"] }

[features]
wasm = ["automerge/wasm"]
default = []

[dev-dependencies]
