[package]
name = "db-proto"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "DB Proto"

[lib]
name = "db_proto"

[dependencies]
# gRPC
prost = { workspace = true, features = [] }
prost-types = { workspace = true, features = [] }
tonic = { workspace = true, features = ["codegen"] }
tonic-prost = { workspace = true, features = [] }

[build-dependencies]
tonic-prost-build = { version = "0.14", default-features = false }

[dev-dependencies]

[package.metadata.cargo-machete]
# Ignore generated code crates
ignored = ["prost", "tonic-prost"]

[features]
default = ["file-descriptor-set"]
file-descriptor-set = []
