[package]
name = "db-engine-automerge"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "db_engine_automerge"
path = "src/lib.rs"

[dependencies]
# internal dependencies
db-btree = { path = "../db-btree", default-features = false, features = [] }
db-btree-automerge = { path = "../db-btree-automerge", default-features = false, features = [] }
db-engine = { path = "../db-engine", default-features = false, features = ["std"] }
db-value = { path = "../db-value", default-features = false, features = ["std"] }

# external dependencies
automerge = { version = "0.9", default-features = false, features = [] }
async-stream = { version = "0.3", default-features = false, features = [] }
futures = { version = "0.3", default-features = false, features = ["std"] }
postcard = { version = "1.1", default-features = false, features = ["alloc"] }
uuid = { version = "1.23", default-features = false, features = ["v7"] }

[dev-dependencies]
# internal dependencies
db-engine-redb = { path = "../db-engine-redb", default-features = false, features = [] }
db-query = { path = "../db-query", default-features = false, features = [] }
db-schema = { path = "../db-schema", default-features = false, features = [] }

# external dependencies
futures = { version = "0.3", default-features = false, features = ["executor"] }
redb = { version = "4.3", default-features = false, features = ["uuid"] }
