[package]
name = "db-redb"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "db_redb"

[dependencies]
db-engine = { path = "../db-engine", default-features = true }
async-stream = { version = "0.3", default-features = false, features = [] }
futures = { version = "0.3", default-features = false, features = ["std"] }
async-lock = { version = "3.4", default-features = false, features = [] }
redb = { version = "4.0", default-features = false, features = [] }
dashmap = { version = "6.2", default-features = false, features = [] }

[dev-dependencies]

[features]
default = []
