[package]
name = "db-examples-util"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "DB Examples Utility Crate"

[lib]
path = "src/lib.rs"
name = "db_examples_util"

[dependencies]
# internal dependencies
db-engine = { path = "../db-engine", default-features = false, features = ["std"] }
db-query = { path = "../db-query", default-features = true }

rustyline = { version = "18.0" }

[build-dependencies]

[dev-dependencies]
