[package]
name = "db-examples-util"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "DB Examples Utility Crate"

[lib]
path = "src/lib.rs"
name = "db_examples_util"

[dependencies]
# internal dependencies
db-btree = { path = "../db-btree", default-features = true }
db-value = { path = "../db-value", default-features = true }
db-query = { path = "../db-query", default-features = true }
db-engine = { path = "../db-engine", default-features = true }
db-sql-translator = { path = "../db-sql-translator", default-features = true }

uuid = { version = "1.23", features = ["v7"] }
rustyline = { version = "18.0" }

[build-dependencies]

[dev-dependencies]
