[package]
name = "db-engine"
description = "Engine layer of the database"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
path = "src/lib.rs"
name = "db_engine"

[features]
default = ["std", "in-memory", "automerge", "redb"]
std = [
  "futures/std",
  "uuid/std",
  "async-lock/std",
  "serde/std",
  "serde_json/std",
  "db-schema/std",
  "db-btree/std",
  "db-value/std",
  "db-query/std"
]
redb = ["dep:db-redb", "dep:redb", "db-value/redb", "std"]
automerge = ["dep:db-automerge", "dep:automerge", "dep:autosurgeon", "db-value/automerge", "std"]
in-memory = ["dep:async-stream", "db-btree/in-memory"]
wasm = ["dep:tsify", "dep:serde-wasm-bindgen", "dep:wasm-bindgen", "automerge/wasm", "db-value/wasm", "db-query/wasm", "db-schema/wasm"]

[dependencies]
# internal dependencies
db-btree = { path = "../db-btree", default-features = false, features = [] }
db-value = { path = "../db-value", default-features = false, features = [] }
db-query = { path = "../db-query", default-features = false, features = [] }
db-schema = { path = "../db-schema", default-features = false, features = [] }

# automerge
db-automerge = { path = "../db-automerge", default-features = false, features = [], optional = true }
automerge = { version = "0.10", default-features = false, features = [], optional = true }
autosurgeon = { version = "0.12", default-features = false, features = ["uuid"], optional = true }

# redb
db-redb = { path = "../db-redb", default-features = false, features = [], optional = true }
redb = { version = "4.1", default-features = false, features = ["uuid"], optional = true }

async-stream = { version = "0.3", default-features = false, features = [
], optional = true }
async-lock = { version = "3.4", default-features = false, features = [
] }
futures = { version = "0.3", default-features = false, features = [] }
serde = { version = "1.0", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
thiserror = { version = "2.0", default-features = false }
uuid = { version = "1.23", default-features = false, features = ["serde"] }

# Optional TS generation + serde for tsify
tsify = { version = "0.5", default-features = false, features = [
  "js",
], optional = true }
serde-wasm-bindgen = { version = "0.6", default-features = false, optional = true }
wasm-bindgen = { version = "0.2", default-features = false, features = [
  "std",
], optional = true }

[dev-dependencies]
futures = { version = "0.3", default-features = false, features = ["executor"] }
