syntax = "proto3";
package db;

import "google/protobuf/empty.proto";


// ================================================
// Statement Start
// crates/db-engine/src/query.rs
// ================================================

message Statement {
}

message Value {
}

// ================================================
// Statement End
// ================================================

message StatementRequest {
    Statement statement = 1;
}

message StatementResponseColumn {
  string name = 1;
  optional string source_table = 2;
  optional uint64 source_column_index = 3;
}

message StatementResponse {
  repeated Value rows = 1;
  repeated StatementResponseColumn columns = 2;
}

service StatementService {
    rpc Execute (StatementRequest) returns (StatementResponse);
}