[package]
name = "db-engine-redb"
version.workspace = true
publish = false
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "db_engine_redb"
path = "src/lib.rs"

[dependencies]
# internal dependencies
db-btree = { path = "../db-btree", default-features = false, features = [] }
db-btree-redb = { path = "../db-btree-redb", default-features = false, features = [] }
db-engine = { path = "../db-engine", default-features = false, features = ["std"] }
db-value = { path = "../db-value", default-features = false, features = ["redb", "std"] }

# external dependencies
async-stream = { version = "0.3", default-features = false, features = [] }
futures = { version = "0.3", default-features = false, features = ["std"] }
redb = { version = "4.1", default-features = false, features = ["uuid"] }
