[package]
name = "db-macros"
description = "Derive macros for db"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[dependencies]
quote = { version = "1.0", default-features = false, features = [] }
syn = { version = "2.0", default-features = false, features = ["derive", "parsing", "proc-macro"] }

[dev-dependencies]
db-value = { path = "../db-value", default-features = false, features = [] }
uuid = { version = "1.23", default-features = false, features = [] }
