[package]
name = "db-test"
publish = false
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lib]
name = "db_test"
path = "src/lib.rs"

[dependencies]
# Internal dependencies
db-engine = { path = "../db-engine", default-features = false, features = ["in-memory", "std"] }
db-engine-automerge = { path = "../db-engine-automerge", default-features = false, features = [] }
db-engine-redb = { path = "../db-engine-redb", default-features = false, features = [] }
db-sql-translator = { path = "../db-sql-translator", default-features = false, features = ["std"] }
db-value = { path = "../db-value", default-features = false, features = ["std"] }

# External dependencies
futures = { version = "0.3", default-features = false, features = ["executor"] }
redb = { version = "4.1", default-features = false, features = ["uuid"] }
